"""FastAPI response schemas for M8 documentation endpoints.

This module defines Pydantic models used by the FastAPI routes that expose the
M8 fake-data pipeline.

These models make the automatic FastAPI documentation clearer because each
endpoint has a declared response shape.
"""

from pydantic import BaseModel, Field


class EndpointInfo(BaseModel):
    """Describe one API endpoint exposed by the application."""

    path: str = Field(description="Endpoint path.")
    method: str = Field(description="HTTP method used by the endpoint.")
    summary: str = Field(description="Short description of the endpoint.")
    purpose: str = Field(description="Why the endpoint exists.")


class SchemaInfo(BaseModel):
    """Describe one main schema or model used by the pipeline."""

    name: str = Field(description="Schema or model name.")
    layer: str = Field(description="Project layer where the schema is used.")
    purpose: str = Field(description="What the schema represents.")
    important_fields: list[str] = Field(
        description="Important fields exposed by the schema."
    )


class M8SampleDataSummaryResponse(BaseModel):
    """Response model for the M8 fake input data summary."""

    source_folder: str = Field(description="Folder containing the fake input files.")
    sample_submissions_count: int = Field(description="Number of sample rows read.")
    assay_results_count: int = Field(description="Number of assay result rows read.")
    shipments_count: int = Field(description="Number of shipment rows read.")
    workflow_events_count: int = Field(description="Number of workflow event rows read.")
    uses_real_data: bool = Field(
        description="Whether the endpoint uses real company data."
    )
    loads_postgresql: bool = Field(
        description="Whether the endpoint loads data into PostgreSQL."
    )


class M8PipelineSummaryResponse(BaseModel):
    """Response model for the M8 end-to-end fake pipeline summary."""

    sample_submissions_read: int = Field(description="Number of sample records read.")
    assay_results_read: int = Field(description="Number of assay result records read.")
    shipments_read: int = Field(description="Number of shipment records read.")
    workflow_events_read: int = Field(description="Number of workflow event records read.")
    rejected_records_created: int = Field(
        description="Number of rejected records created from failed validations."
    )
    pipeline_stage: str = Field(description="Current pipeline stage represented.")
    uses_real_data: bool = Field(
        description="Whether the pipeline uses real company data."
    )
    loads_postgresql: bool = Field(
        description="Whether the pipeline inserts records into PostgreSQL."
    )


class RejectedRecordsSummaryResponse(BaseModel):
    """Response model for rejected-record summary information."""

    rejected_records_created: int = Field(
        description="Number of rejected records created from failed validations."
    )
    output_file: str = Field(description="Path of the generated rejected-record CSV.")
    output_is_generated: bool = Field(
        description="Whether the output file is generated by the pipeline."
    )
    tracked_by_git: bool = Field(
        description="Whether the generated output file should be committed to Git."
    )